### ISSUE TITLE
[Help] 2020-02-05T09:50:42.258399+00:00 app[web.1]: Error: libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wahengchang** [pastak/docker-heroku-nodejs-opencv-sample#1]
Hi Pastak, I spent so much time in deploying an project with `opencv4nodejs` dependency to heroku, and so bad luck that still in failure. 

I found your repo, and clone it, release it to heroku, steps is shown here:
`https://github.com/wahengchang/nodejs-docker-heroku`
![image](https://user-images.githubusercontent.com/5538753/73831777-d8776980-4841-11ea-8a46-e04275d8199a.png)

but i met the error
![image](https://user-images.githubusercontent.com/5538753/73831815-e7f6b280-4841-11ea-978e-f9a7000e0685.png)

**Comment by wahengchang** [comment]
```
Uninstall with heroku plugins:uninstall heroku-docker and install heroku-container-tools with heroku plugins:install heroku-container-tools2020-02-05T09:50:33.131507+00:00 app[web.1]: npm ERR!     npm owner ls docker-heroku-nodejs-opencv-sample
2020-02-05T09:50:33.131509+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2020-02-05T09:50:33.131511+00:00 app[web.1]: 
2020-02-05T09:50:33.131513+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2020-02-05T09:50:33.131515+00:00 app[web.1]: npm ERR!     /app/user/npm-debug.log
2020-02-05T09:50:33.236023+00:00 heroku[web.1]: State changed from starting to crashed
2020-02-05T09:50:33.239995+00:00 heroku[web.1]: State changed from crashed to starting
2020-02-05T09:50:33.212153+00:00 heroku[web.1]: Process exited with status 1
2020-02-05T09:50:38.501090+00:00 heroku[web.1]: Starting process with command `cd /app/user && bin/web`
2020-02-05T09:50:41.825400+00:00 app[web.1]: 
2020-02-05T09:50:41.825419+00:00 app[web.1]: > docker-heroku-nodejs-opencv-sample@1.0.0 start /app/user
2020-02-05T09:50:41.825421+00:00 app[web.1]: > node index.js
2020-02-05T09:50:41.825424+00:00 app[web.1]: 
2020-02-05T09:50:42.258379+00:00 app[web.1]: module.js:355
2020-02-05T09:50:42.258392+00:00 app[web.1]: Module._extensions[extension](this, filename);
2020-02-05T09:50:42.258394+00:00 app[web.1]: ^
2020-02-05T09:50:42.258397+00:00 app[web.1]: 
2020-02-05T09:50:42.258399+00:00 app[web.1]: Error: libpng12.so.0: cannot open shared object file: No such file or directory
2020-02-05T09:50:42.258401+00:00 app[web.1]: at Error (native)
2020-02-05T09:50:42.258404+00:00 app[web.1]: at Module.load (module.js:355:32)
2020-02-05T09:50:42.258406+00:00 app[web.1]: at Function.Module._load (module.js:310:12)
2020-02-05T09:50:42.258408+00:00 app[web.1]: at Module.require (module.js:365:17)
2020-02-05T09:50:42.258410+00:00 app[web.1]: at require (module.js:384:17)
2020-02-05T09:50:42.258413+00:00 app[web.1]: at Object.<anonymous> (/app/user/node_modules/opencv/lib/bindings.js:4:15)
2020-02-05T09:50:42.258415+00:00 app[web.1]: at Module._compile (module.js:434:26)
```

**Comment by pastak** [comment]
I clone this repo and run docker:release then success it. 

Log is here

```
docker-heroku-nodejs-opencv-sample[master] % heroku docker:release -a heroku-nodejs-opencv-sample
(node:17471) Error Plugin: heroku-docker: files attribute must be specified in /Users/pastak/.local/share/heroku/node_modules/heroku-docker/package.json
module: @oclif/config@1.13.2
plugin: heroku-docker
root: /Users/pastak/.local/share/heroku/node_modules/heroku-docker
See more details with DEBUG=*
 ›   Warning: heroku update available from 7.30.1 to 7.38.1.
(node:17471) Error Plugin: heroku-docker: files attribute must be specified in /Users/pastak/.local/share/heroku/node_modules/heroku-docker/package.json
module: @oclif/plugin-legacy@1.1.4
plugin: heroku-docker
root: /Users/pastak/.local/share/heroku/node_modules/heroku-docker
See more details with DEBUG=*
heroku-docker is deprecated.
Uninstall with heroku plugins:uninstall heroku-docker and install heroku-container-tools with heroku plugins:install heroku-container-toolsRemote addons:  (0)
Local addons:  (0)
Missing addons:  (0)
Creating local slug...
Building web
Step 1/2 : FROM pastak/docker-heroku-nodejs-opencv
latest: Pulling from pastak/docker-heroku-nodejs-opencv
Image docker.io/pastak/docker-heroku-nodejs-opencv:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
Digest: sha256:4c5b12775889b0c207638ccb42730c5c6b0161e0ed8ad64da137fc253b6fc086
Status: Downloaded newer image for pastak/docker-heroku-nodejs-opencv:latest
# Executing 3 build triggers
 ---> Running in b9a693a50209
npm WARN package.json docker-heroku-nodejs-opencv-sample@1.0.0 No description
npm WARN package.json docker-heroku-nodejs-opencv-sample@1.0.0 No README data
npm WARN deprecated datauri@0.8.0: Datauri 2.0 released. See more in https://github.com/data-uri/datauri/releases/tag/v2.0.0
npm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later
npm WARN deprecated mimer@0.2.3: Mimer 1.0 released. See more in https://github.com/data-uri/mimer/releases/tag/v1.0.0

> opencv@4.0.0 install /app/user/node_modules/opencv
> node-pre-gyp install --fallback-to-build

make: Entering directory `/app/user/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
../src/Matrix.cc: In member function 'virtual void AsyncToBufferWorker::HandleOKCallback()':
../src/Matrix.cc:705:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../node_modules/nan/nan.h:1740) [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
../src/Matrix.cc: In member function 'virtual void AsyncSaveWorker::HandleOKCallback()':
../src/Matrix.cc:975:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../node_modules/nan/nan.h:1740) [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
  CXX(target) Release/obj.target/opencv/src/OpenCV.o
  CXX(target) Release/obj.target/opencv/src/CascadeClassifierWrap.o
../src/CascadeClassifierWrap.cc: In member function 'virtual void AsyncDetectMultiScale::HandleOKCallback()':
../src/CascadeClassifierWrap.cc:101:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../node_modules/nan/nan.h:1740) [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
  CXX(target) Release/obj.target/opencv/src/Contours.o
  CXX(target) Release/obj.target/opencv/src/Point.o
  CXX(target) Release/obj.target/opencv/src/VideoCaptureWrap.o
../src/VideoCaptureWrap.cc: In member function 'virtual void AsyncVCWorker::HandleOKCallback()':
../src/VideoCaptureWrap.cc:176:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../node_modules/nan/nan.h:1740) [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
  CXX(target) Release/obj.target/opencv/src/CamShift.o
  CXX(target) Release/obj.target/opencv/src/HighGUI.o
  CXX(target) Release/obj.target/opencv/src/FaceRecognizer.o
../src/FaceRecognizer.cc: In member function 'virtual void PredictASyncWorker::HandleOKCallback()':
../src/FaceRecognizer.cc:313:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../node_modules/nan/nan.h:1740) [-Wdeprecated-declarations]
     callback->Call(1, argv);
                           ^
  CXX(target) Release/obj.target/opencv/src/Features2d.o
../src/Features2d.cc: In member function 'virtual void AsyncDetectSimilarity::HandleOKCallback()':
../src/Features2d.cc:90:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../node_modules/nan/nan.h:1740) [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
  CXX(target) Release/obj.target/opencv/src/BackgroundSubtractor.o
  CXX(target) Release/obj.target/opencv/src/Constants.o
  CXX(target) Release/obj.target/opencv/src/Calib3D.o
  CXX(target) Release/obj.target/opencv/src/ImgProc.o
  CXX(target) Release/obj.target/opencv/src/Stereo.o
  CXX(target) Release/obj.target/opencv/src/LDAWrap.o
  SOLINK_MODULE(target) Release/obj.target/opencv.node
  COPY Release/opencv.node
  COPY /app/user/node_modules/opencv/build/opencv/v4.0.0/Release/node-v46-linux-x64/opencv.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/app/user/node_modules/opencv/build'
koa-router@5.4.2 node_modules/koa-router
├── methods@1.1.2
├── co@4.6.0
├── path-to-regexp@1.8.0 (isarray@0.0.1)
├── http-errors@1.7.3 (toidentifier@1.0.0, statuses@1.5.0, inherits@2.0.4, setprototypeof@1.1.1, depd@1.1.2)
└── debug@2.6.9 (ms@2.0.0)

datauri@0.8.0 node_modules/datauri
├── mimer@0.2.3
└── rsvp@3.6.2

koa-static@2.1.0 node_modules/koa-static
├── debug@2.6.9 (ms@2.0.0)
└── koa-send@3.3.0 (co@4.6.0, resolve-path@1.4.0, mz@2.7.0)

koa@1.7.0 node_modules/koa
├── error-inject@1.0.0
├── only@0.0.2
├── destroy@1.0.4
├── escape-html@1.0.3
├── koa-compose@2.5.1
├── content-type@1.0.4
├── vary@1.1.2
├── parseurl@1.3.3
├── fresh@0.5.2
├── co@4.6.0
├── koa-is-json@1.0.0
├── statuses@1.5.0
├── delegates@1.0.0
├── http-errors@1.7.3 (toidentifier@1.0.0, inherits@2.0.4, setprototypeof@1.1.1, depd@1.1.2)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── type-is@1.6.18 (media-typer@0.3.0)
├── content-disposition@0.5.3 (safe-buffer@5.1.2)
├── debug@2.6.9 (ms@2.0.0)
├── accepts@1.3.7 (negotiator@0.6.2)
├── http-assert@1.4.1 (deep-equal@1.0.1)
├── mime-types@2.1.26 (mime-db@1.43.0)
├── composition@2.3.0 (any-promise@1.3.0)
└── cookies@0.8.0 (depd@2.0.0, keygrip@1.1.0)

koa-body@1.7.0 node_modules/koa-body
├── extend@1.3.0
├── formidable@1.0.17
└── co-body@5.2.0 (inflation@2.0.0, qs@6.9.1, type-is@1.6.18, raw-body@2.4.1)

opencv@4.0.0 node_modules/opencv
├── buffers@0.1.1
└── nan@2.14.0
Removing intermediate container b9a693a50209
 ---> 7a4d40738840
Step 2/2 : CMD bin/web
 ---> Running in 272fce3b64a3
Removing intermediate container 272fce3b64a3
 ---> 8b45f7b8eb01
Successfully built 8b45f7b8eb01
Successfully tagged docker-heroku-nodejs-opencv-sample_web:latest
extracting slug from container...
creating remote slug...
language-pack: heroku-container-tools (pastak/docker-heroku-nodejs-opencv)
remote process types: { web: 'cd /app/user && bin/web' }
uploading slug [====================] 100% of 81 MB, 0.0s
releasing slug...
Successfully released heroku-nodejs-opencv-sample!
```
